# Generated by Django 2.0.7 on 2022-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='premios',
            field=models.TextField(default='No tiene premios'),
        ),
    ]
