# Generated by Django 2.1.7 on 2022-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_auto_20220825_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.IntegerField(),
        ),
    ]
